# TorchServe frontend parameters
minWorkers: 1
maxWorkers: 10
maxBatchDelay: 100
responseTimeout: 120
parallelType: "tp"
deviceType: "gpu"
# example of user specified GPU deviceIds
deviceIds: [ 0,1,2,3 ] # seting CUDA_VISIBLE_DEVICES

torchrun:
  nproc-per-node: 4

# TorchServe Backend parameters
deepspeed:
  config: ds-config.json
  checkpoint: checkpoints.json

handler:
  model_name: "text2sql"
  model_path: "/date/bruce/workspace/RESDSQL-Coding/models/text2sql-t5-3b/checkpoint-103292"
  max_length: 512
  max_new_tokens: 100
  manual_seed: 40
  num_beams: 1
  num_return_sequences: 1
  use_contents: False
  add_fk_info: True
  topk_table_num: 4
  topk_column_num: 5
  classifier_url: 'http://localhost:3100/predictions/classifier'
